#-------------------------------
# General Site Settings
baseurl: ""
url: "https://datart-lab.com"
port: 4001


#-------------------------------
# Build Settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-sitemap


#-------------------------------
# Collections
collections:
  pages:
    output: true
    permalink: /:name
  works:
    output: false

# Pages Path
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

sass:
  sass_dir: _sass
  style: compressed
